# exposes postgres directly, other services via caddy

services:
  postgres:
    networks:
      - default

  pgadmin:
    networks:
      - caddy
      - default
    labels:
      caddy: admin.${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 80}}"

  postgrest:
    networks:
      - caddy
      - default
    labels:
      caddy: ${PGRST_OPENAPI_SERVER_PROXY_URI}
      caddy.reverse_proxy: "{{upstreams 3000}}"

  swaggerui:
    networks:
      - caddy
      - default
    labels:
      caddy: ${PGRST_OPENAPI_SERVER_PROXY_URI}
      caddy.1_handle_path: /docs/*
      caddy.1_handle_path.reverse_proxy: "{{upstreams 8080}}"

  keycloak:
    networks:
      - caddy
      - default
    labels:
      caddy: ${KEYCLOAK_SERVER}
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  # Add caddy as an external network.
  caddy:
    external: true


